cTID = function(s) { return app.charIDToTypeID(s); };
sTID = function(s) { return app.stringIDToTypeID(s); };

makeRectangle();

function makeRectangle() {
  var desc1 = new ActionDescriptor();
  var ref1 = new ActionReference();
  ref1.putClass(sTID("contentLayer"));
  desc1.putReference(cTID('null'), ref1);
  var desc2 = new ActionDescriptor();
  var desc3 = new ActionDescriptor();
  var desc4 = new ActionDescriptor();
  desc4.putDouble(cTID('Rd  '), 255);
  desc4.putDouble(cTID('Grn '), 255);
  desc4.putDouble(cTID('Bl  '), 255);
  desc3.putObject(cTID('Clr '), sTID("RGBColor"), desc4);
  desc2.putObject(cTID('Type'), sTID("solidColorLayer"), desc3);
  var desc5 = new ActionDescriptor();
  desc5.putInteger(sTID("unitValueQuadVersion"), 1);
  desc5.putUnitDouble(cTID('Top '), cTID('#Pxl'), 1625);
  desc5.putUnitDouble(cTID('Left'), cTID('#Pxl'), 1404);
  desc5.putUnitDouble(cTID('Btom'), cTID('#Pxl'), 2048);
  desc5.putUnitDouble(cTID('Rght'), cTID('#Pxl'), 3192);
  desc5.putUnitDouble(sTID("topRight"), cTID('#Pxl'), 0);
  desc5.putUnitDouble(sTID("topLeft"), cTID('#Pxl'), 0);
  desc5.putUnitDouble(sTID("bottomLeft"), cTID('#Pxl'), 0);
  desc5.putUnitDouble(sTID("bottomRight"), cTID('#Pxl'), 0);
  desc2.putObject(cTID('Shp '), cTID('Rctn'), desc5);
  var desc6 = new ActionDescriptor();
  desc6.putInteger(sTID("strokeStyleVersion"), 2);
  desc6.putBoolean(sTID("strokeEnabled"), true);
  desc6.putBoolean(sTID("fillEnabled"), false);
  desc6.putUnitDouble(sTID("strokeStyleLineWidth"), cTID('#Pxl'), 1);
  desc6.putUnitDouble(sTID("strokeStyleLineDashOffset"), cTID('#Pnt'), 0);
  desc6.putDouble(sTID("strokeStyleMiterLimit"), 100);
  desc6.putEnumerated(sTID("strokeStyleLineCapType"), sTID("strokeStyleLineCapType"), sTID("strokeStyleButtCap"));
  desc6.putEnumerated(sTID("strokeStyleLineJoinType"), sTID("strokeStyleLineJoinType"), sTID("strokeStyleMiterJoin"));
  desc6.putEnumerated(sTID("strokeStyleLineAlignment"), sTID("strokeStyleLineAlignment"), sTID("strokeStyleAlignCenter"));
  desc6.putBoolean(sTID("strokeStyleScaleLock"), false);
  desc6.putBoolean(sTID("strokeStyleStrokeAdjust"), false);
  var list1 = new ActionList();
  desc6.putList(sTID("strokeStyleLineDashSet"), list1);
  desc6.putEnumerated(sTID("strokeStyleBlendMode"), cTID('BlnM'), cTID('Nrml'));
  desc6.putUnitDouble(sTID("strokeStyleOpacity"), cTID('#Prc'), 100);
  var desc7 = new ActionDescriptor();
  var desc8 = new ActionDescriptor();
  desc8.putDouble(cTID('Rd  '), 0);
  desc8.putDouble(cTID('Grn '), 0);
  desc8.putDouble(cTID('Bl  '), 0);
  desc7.putObject(cTID('Clr '), sTID("RGBColor"), desc8);
  desc6.putObject(sTID("strokeStyleContent"), sTID("solidColorLayer"), desc7);
  desc6.putDouble(sTID("strokeStyleResolution"), 300);
  desc2.putObject(sTID("strokeStyle"), sTID("strokeStyle"), desc6);
  desc1.putObject(cTID('Usng'), sTID("contentLayer"), desc2);
  desc1.putInteger(cTID('LyrI'), 82);
  executeAction(cTID('Mk  '), desc1, DialogModes.NO);
};
